import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import './index.css';

// Import service worker development utilities
import './utils/swDevUtils';

// Register service worker for PWA functionality using virtual:pwa-register
// Only register in production, not during development to avoid caching issues
if ('serviceWorker' in navigator && import.meta.env.MODE === 'production') {
  window.addEventListener('load', async () => {
    try {
      // Dynamically import the service worker registration
      // @ts-ignore - virtual:pwa-register is a virtual module generated by Vite PWA
      const { registerSW } = await import('virtual:pwa-register');
      
      // Register the service worker with proper base URL resolution
      registerSW({
        immediate: true,
        onRegisteredSW(swUrl: string, r: ServiceWorkerRegistration | undefined) {
          console.log('SW registered: ', swUrl, r);
        },
        onRegisterError(error: Error) {
          console.log('SW registration error: ', error);
        },
        onOfflineReady() {
          console.log('App ready to work offline');
        },
        onNeedRefresh() {
          console.log('New content available, please refresh');
        }
      });
    } catch (error) {
      console.log('SW registration failed: ', error);
    }
  });
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);